### ISSUE TITLE
2 Angaben

### ISSUE THREAD

**Issue by sma-h** [THK-IB/MALIS-20.3-WPM_T9_Ina_Bartnitzek#3]
Könntest Du auch noch im Abschnitt "Einsatzgebiet Aktenaussonderung" die verwendete SAP-Software konkretisieren? R3?
Ich bin mir auch nicht sicher, um welche Anschreiben es bei "automatisiertes Befüllen der Anschreiben" geht?

**Comment by THK-IB** [comment]
SAP HR heißt es bei uns. SAP Human Capital Management ist wohl der offizielle Modultitel. Außerdem wird noch Materialwirschaft und Prodis genutzt. Aber die sind an der Stelle nicht von Belang.

Die Anschreiben habe ich nun noch erläutert und ihnen eine Fußnote gegönnt.
