### ISSUE TITLE
Feedback: Gefält mir!

### ISSUE THREAD

**Issue by sma-h** [THK-IB/MALIS-20.3-WPM_T9_Ina_Bartnitzek#5]
Ich finde den Text gut strukturiert und nachvollziehbar. Er zeigt nicht nur die Bereiche des ZAM in denen Softwareeinsatz die Arbeit erleichtern könnte, sondern auch die, bei der Softwarelösungen schon erfolgreich umgesetzt worden sind. Überschaubar durch das Inhaltsverzeichnis und anschaubarer durch die Screenshots.

**Comment by THK-IB** [comment]
Danke.
