### ISSUE TITLE
README-File

### ISSUE THREAD

**Issue by sma-h** [THK-IB/MALIS-20.3-WPM_T9_Ina_Bartnitzek#6]
Die Idee die Aufgabenbeschreibung hier rein zu kopieren finde ich sehr gut! Beschreibt wunderbar den Inhalt und Zweck der Aufgabe.
Die Anmerkungen erschließen sich mir nur teilweise. Möchtest Du sie noch ein bisschen konkretisieren (bes. da, wo es um das Branch-Thema geht)? Sind das Fragen an den Dozenten?

**Comment by THK-IB** [comment]
Hab README im unteren Teil als Gedächtnisstütze genutzt. Wollte keine Änderungen (Master/Main) angehen, bevor nicht Pull request, Issues und Überarbeitung durch sind. Um recherchierte Ursache und Lösungsansätze nicht zu vergessen, habe ich es dort hinterlegt. Werd heute oder morgen Hr. Förstner dazu anschreiben.
